# clears the screen
# cleans the old executable if exists
# compiles code
# runs executable in that order.
all: clear clean compile run

clear:
	@clear

clean:
	@rm -rf a.out

compile:
	@g++ -std=c++11 *.cpp

run:
	@./a.out

